<Project>
  <PropertyGroup>
    <VersionPrefix>0.27.0</VersionPrefix>
    <VersionSuffix>beta</VersionSuffix>
    <Version>$(VersionPrefix)-$(VersionSuffix)</Version>
    <AssemblyVersion>$(VersionPrefix).0</AssemblyVersion>
    <FileVersion>$(VersionPrefix).0</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <Authors>Adler Rodríguez de la gala Soberanis</Authors>
    <Company>EXOTARA</Company>
    <Product>Sakura</Product>
    <Description>Sakura — Tu Windows, en flor.</Description>
    <Copyright>Copyright © 2026</Copyright>
    <NeutralLanguage>es-MX</NeutralLanguage>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
